### ISSUE TITLE
Exception to no-unused-vars for `apos`

### ISSUE THREAD

**Issue by abea** [punkave/eslint-config-punkave#3]
I'm thinking we should add an exception to [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars#varsignorepattern) to not throw an error in app.js for not using `apos`.

> "no-unused-vars": ["error", { "varsIgnorePattern": "apos" }]

**Comment by bgantick** [comment]
Agreed,  would approve this as a PR

**Comment by austinstarin** [comment]
Thanks @abea. Anything else, like `$` or `_` should be done in `.eslintignore` at project level if needed.

**Comment by austinstarin** [comment]
Please make a PR for this 👍
