### ISSUE TITLE
No space after function keyword

### ISSUE THREAD

**Issue by abea** [punkave/eslint-config-punkave#7]
@boutell brought up that we shouldn't be getting an error for a missing space before function parentheses, as the "no space" approach is used throughout Apostrophe.

Right now we're inheriting the rule to require a space from the standard config: e.g., `function () { ... }`. The suggestion would be to set our rule to never have a space before function parens: e.g., `function() { ... }`.

Rule: https://eslint.org/docs/rules/space-before-function-paren

**Comment by austinstarin** [comment]
@boutell @abea The reason we choose standard was so we don't have to bikeshed about this sort of thing.

**Comment by abea** [comment]
Just the messenger on this one. Happy to stay as-is, especially since I don't think we're actively using this for Apostrophe 2.0 anyway.

**Comment by austinstarin** [comment]
Are we okay to close this? @abea

**Comment by abea** [comment]
Sure.
